Your meaningful commit message

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,3 +1,8 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 pnpm test || (echo "Tests failed! Push aborted." && exit 1)
+
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+pnpm run lint || (echo "Push aborted, please remove comments!" && exit 1)
