eslint rules update

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,18 +1,8 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
-
-pnpm test || (
-        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
-                Unit Test Failed. Make the required changes listed above, add changes and try to fix again.'
-        false; 
-)
+pnpm test || (echo "Tests failed! Push aborted." && exit 1)
 
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-pnpm lint-staged ||
-(
-    echo '🤢🤮🤢🤮 Its F**KING RAW - Your code looks disgusting. 🤢🤮🤢🤮
-            lint Check Failed. Refactor your code again!.';
-    false;
-)
+pnpm lint-staged || (echo "Code is not clean!" && exit 1)
