push restrictions

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,13 +2,13 @@
 . "$(dirname "$0")/_/husky.sh"
 pnpm test || (echo "Tests failed! Push aborted." && exit 1)
 
-#!/bin/sh (#To check code format & unused variable, imports, exports etc.. before push)
-. "$(dirname "$0")/_/husky.sh"
+#!/bin/sh (#Run the test-all script to ensure all tests are run before push)
+pnpm run test-all || (echo "Tests failed! Push aborted." && exit 1)
 
+#!/bin/sh (#To check code format & unused variable, imports, exports etc.. before push)
 pnpm lint-staged || (echo "Code is not clean!" && exit 1)
 
 #!/bin/sh (#To prevent frequent push within 5 minutes)
-. "$(dirname "$0")/_/husky.sh"
 
 LAST_PUSH_FILE=".git/last_push_time"
 
